-- Create table for global configuration
CREATE TABLE IF NOT EXISTS public.config (
    key TEXT PRIMARY KEY,
    value TEXT
);

-- Insert default values if not exists
INSERT INTO public.config (key, value) VALUES
    ('points_ratio', '1'),
    ('kiosk_name', 'KioskoApp')
ON CONFLICT (key) DO NOTHING;

-- Create table for prizes management
CREATE TABLE IF NOT EXISTS public.prizes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    points INTEGER NOT NULL,
    active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert default prizes
INSERT INTO public.prizes (name, points) VALUES
    ('Bebida Gratis', 20),
    ('Descuento 10%', 50),
    ('Producto Sorpresa', 100)
ON CONFLICT DO NOTHING;

-- Enable RLS (Security) - Optional but good practice
ALTER TABLE public.config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prizes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all access for now" ON public.config FOR ALL USING (true);
CREATE POLICY "Enable all access for now" ON public.prizes FOR ALL USING (true);
