-- Fix for "Error al guardar premio"
-- This script creates the missing 'prizes' and 'config' tables.

CREATE TABLE IF NOT EXISTS public.config (
    key TEXT PRIMARY KEY,
    value TEXT
);

INSERT INTO public.config (key, value) VALUES
    ('points_ratio', '1'),
    ('kiosk_name', 'KioskoApp')
ON CONFLICT (key) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.prizes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    points INTEGER NOT NULL,
    active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS (Security) but allow access
ALTER TABLE public.config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prizes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all access for config" ON public.config FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for prizes" ON public.prizes FOR ALL USING (true) WITH CHECK (true);

-- Insert default prizes if table is empty
INSERT INTO public.prizes (name, points)
SELECT 'Bebida Gratis', 20
WHERE NOT EXISTS (SELECT 1 FROM public.prizes);

INSERT INTO public.prizes (name, points)
SELECT 'Descuento 10%', 50
WHERE NOT EXISTS (SELECT 1 FROM public.prizes WHERE name = 'Descuento 10%');
